### PR TITLE
Added 70. Climbing Stairs Java

### PR DESCRIPTION
**Pull request by PranayChauhan2516**
# Pull Request Template

## Description
Summary:
You are climbing a stair case. It takes n steps to reach to the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
@PranayChauhan2516 This is not the efficient code. Please try to do it in O(1) space.

**Comment by PranayChauhan2516** [comment]
Done!

**Comment by PranayChauhan2516** [comment]
@GouravRusiya30 It is now correct!

**Comment by GouravRusiya30** [comment]
Update Readme for space complexity

**Comment by PranayChauhan2516** [comment]
@GouravRusiya30 Done sir!

**Comment by GouravRusiya30** [comment]
Thanks for contributing @PranayChauhan2516

**Comment by GouravRusiya30** [comment]
Don't forget to give us 🌟

**Pull request merged**
