### PR TITLE
50.Powxn.js

### PR DESCRIPTION
**Pull request by dimshik100**
## Description

Please include a summary of the problem and about the approach to solve the solution. Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lokendra1704 — CHANGES_REQUESTED** [review]
Hello,
Can you implement the main algorithm used behind (x**n)?

**Comment by dimshik100** [comment]
@lokendra1704 

I can implement the algorithm behind (x**n), but I think this solution is also valid as this is a simple ES6 solution.

Maybe I can create another PR with a basic recursive solution?

**Comment by lokendra1704** [comment]
> @lokendra1704
> 
> I can implement the algorithm behind (x**n), but I think this solution is also valid as this is a simple ES6 solution.
> 
> Maybe I can create another PR with a basic recursive solution?

It'll be better if you code the recursive solution in this PR only.

**Comment by dimshik100** [comment]
@lokendra1704 Changed to a recursive solution. 👍

**Review by lokendra1704 — APPROVED** [review]

**Comment by GouravRusiya30** [comment]
Thanks @lokendra1704 for reviewing
Thanks @dimshik100 for the PR

**Pull request merged**
