### PR TITLE
Added python Cdoe for search in sorted and rotated array and added de...

### PR DESCRIPTION
**Pull request by sachinnegi**
…tails to contribution

# Pull Request Template

## Description

Please include a summary of the problem and about the approach to solve the solution. Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
@lokendra1704 Please review all python related PRs.
Thanks !!!

**Comment by sachinnegi** [comment]
Hi,
I have added the solution for https://leetcode.com/problems/search-in-rotated-sorted-array/ in Python.
Please have a look at it and do tell if any improvement is required

**Comment by GouravRusiya30** [comment]
Congratulations on your first PR push @sachinnegi

**Comment by sachinnegi** [comment]
> Congratulations on your first PR push @sachinnegi

Thanks @GouravRusiya30  and @lokendra1704

**Pull request merged**
