### PR TITLE
Added FizzBuzz,WaterBottle,SignOf and BrokenCal Solution In Java

### PR DESCRIPTION
**Pull request by Manish-kasera**
# Pull Request Template

## Description

Please include a summary of the problem and about the approach to solve the solution. Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by GouravRusiya30 — COMMENTED** [review]
- Don't add main methods
- Remove un-necessary package names
- Update README with Problem link and Time/Space Complexity

**Comment by Manish-kasera** [comment]
Okay @GouravRusiya30  I am sure do that

**Comment by Manish-kasera** [comment]
I had made the changes would you please review it
.

**Comment by GouravRusiya30** [comment]
@Manish-kasera 
README file is not updated with correct problem link and time, space complexity

**Comment by Manish-kasera** [comment]
Updated Readme.md File.... Hope everything is Correct @GouravRusiya30

**Review by GouravRusiya30 — APPROVED** [review]

**Pull request merged**
