### PR TITLE
Add solution for 3rd LeetCode Practice Problem - Longest Substring Without Repeating Characters

### PR DESCRIPTION
**Pull request by Git-Harshit**
# Pull Request Template

## Description

This commit adds a well-commented and human-readable Python 3 program to solve the third LeetCode Practice Problem viz., "Longest Substring Without Repeating Characters". The code is judged as Accepted on LeetCode, on 1st August 2021 (the same day this PR is initiated). Have a look, and feel free to suggest any changes or directly improvise the solution.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B
- [X] Directly submitted the solution to LeetCode Judge (Result: Accepted)

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
Thanks Harshit.
Changes looks fine but can you change the file of newly added python code to adhere to the naming conventions ?

**Comment by Git-Harshit** [comment]
Sure @GouravRusiya30, I will update the file name as per your naming convention. 
I have looked into your [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) and [CONTRIBUTING](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/CONTRIBUTING.md) files before, but didn't get any code naming convention. Please let me know your naming convention or share any reference to the file with your naming convention. I will update it soon then.

**Comment by GouravRusiya30** [comment]
Thanks for updating the file name but you haven't updated the README with correct path of file.

**Comment by Git-Harshit** [comment]
Oops, My bad! I did forget about it. Thanks for pinging me on it. I have updated it on the README file too, please have a look again, it should be fine now. 🙂

**Review by GouravRusiya30 — APPROVED** [review]

**Pull request merged**
