### PR TITLE
Create Prime.cpp

### PR DESCRIPTION
**Pull request by divshacker**
# Pull Request

## Prime Number Code

This is the code which is use to find out the prime numbers from 1 to given input limit. 
The Approach is easily understandable  from the code itself.
There is no specific dependency needed as such  for the code any standard compiler can run this code easily.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
NO
- [Y] Added problem & solution under correct topic.
- [N] Specified Space & Time complexity.
- [Y] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [N] Test A
- [N] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [Y ] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [N] I have commented my code so that it is easy to understand
- [N] I have made corresponding changes to the documentation
- [Y] My changes generate no new warnings
- [Y] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
@divshacker is this a Leetcode problem ?

**Comment by divshacker** [comment]
No this is not a leet code problem .
I have added a prime number finding program. This is not a leet code program

**Comment by GouravRusiya30** [comment]
@divshacker Check this repository README
This is all about Leetcode problems. We will not except any such random program.

Rejecting this PR

**Comment by divshacker** [comment]
OK Thank You

**Pull request closed without merging**
