### PR TITLE
ADD: 162-Leetcode(Find Peak element)

### PR DESCRIPTION
**Pull request by jasbirrajrana**
# Pull Request Template

## Description
I contribute my Leetcode solution of problem 162-Find Peak Element (Arrays). Which I solved using binary search in O(log N) time complexity.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
@jasbirrajrana Thanks for creating your first PR

But I can see there is some errors in the README file because of your changes. Please have a look.

**Comment by GouravRusiya30** [comment]
Screenshot 2021-05-17 at 12 45 03

**Comment by jasbirrajrana** [comment]
@GouravRusiya30 Take a look now :)

**Comment by GouravRusiya30** [comment]
Looks good. Merging !!!

**Pull request merged**
