### PR TITLE
Add DP solution

### PR DESCRIPTION
**Pull request by Dipeshtwis**
What does this PR do:

- I have added the LEETCODE dynamic programming solution
- I solved the easy category problem
- Time Complexity O(n).

Submission info:-

- Runtime - 0ms
- Memory - 5.9mb

### CODE REVIEW

**Review by lokendra1704 — CHANGES_REQUESTED** [review]
Update Readme

**Comment by Dipeshtwis** [comment]
The update includes:

- Updated readme

please resolve the conflicts and merge this pull request if you find this solution good

Thanks

**Comment by GouravRusiya30** [comment]
Update readme to resolve conflicts

**Comment by GouravRusiya30** [comment]
We are maintaining a single row for the same problem with different Programming languages. You can use "<br>" to achieve this

**Pull request closed without merging**
