### PR TITLE
Cpp solution

### PR DESCRIPTION
**Pull request by trivediavinash**
# Pull Request Template

## Description
Given an integer array nums , find the contiguous subarray (containing at least one number) which has the largest sum and return its sum. The approach is simple we can use the kadane's Algorithm and problem can be solved with O(N ) time complexity and O(1) space complexity. 

## Dependencies
Software Tool : Vs code ,Notepad
Programming language : C++
## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [✔️ ] Added problem & solution under correct topic.
- [✔️ ] Specified Space & Time complexity.
- [✔️ ] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [✔️  ] Test A
- [✔️  ] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [✔️  ] My code follows the style guidelines of this project
- [✔️ ] I have performed a self-review of my own code
- [✔️ ] I have commented my code so that it is easy to understand
- [✔️ ] I have made corresponding changes to the documentation
- [✔️] My changes generate no new warnings
- [✔️] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by trivediavinash** [comment]
@GouravRusiya30  Please review my PR.

**Comment by GouravRusiya30** [comment]
@trivediavinash Can you format the code.

**Comment by trivediavinash** [comment]
@GouravRusiya30  i dont know how to make changes  now

**Comment by GouravRusiya30** [comment]
Ok no problem. I am merging

**Pull request merged**
