### PR TITLE
Adding the solution for Redundant Connection

### PR DESCRIPTION
**Pull request by SauravP97**
# Pull Request Template

## Description

- Problem Name : **Redundant Connection**
- Difficulty : Medium

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SauravP97** [comment]
Hey @GouravRusiya30
<p> 
       I have implemented a structured editorial template for the current problem along with code solution. Instead of having one code file for a particular problem, we can have a folder with that problem name and inside of that we can have a Readme.md file describing the editorial for the problem. This will help us in describing the problem in a much efficient way as we can use the feature of showing images and source code snippet in the read me file.
</p>
<p>
       When readers will open a particular problem folder, not only they will be able to have the source code but a detailed editorial with images and code snippets will be presented to them. I am sure, they will be able to visualise the solution better this time.
</p>

#### Talking about the editorial structure, it has three mandatory sections : 
1.  Problem Statement
2.  Solution
3.  Complexity (Time & Space)

Apart from that one can add useful links, images and source code snippets to make the editorial more interesting and easy to understand.

For people who are willing to contribute editorials for a problem, they can adapt this structure. 
Hope it helps !  :smiley: 

My Problem editorial looks like this :man_technologist: 

Screenshot from 2020-10-30 18-02-00
Screenshot from 2020-10-30 18-02-08

**Comment by GouravRusiya30** [comment]
@SauravP97 Awesome !!!
This is what was needed, I really like the idea and we should make it as a new PR Template.

@lokendra1704  What's your view on this ???

**Comment by GouravRusiya30** [comment]
Also, we can add the Editorial link instead of Notes column of our main README.md file.

**Comment by SauravP97** [comment]
Yes @GouravRusiya30, we can add the editorial read me link in the repo's read me (in the table).

**Review by GouravRusiya30 — APPROVED** [review]

**Pull request merged**
