### PR TITLE
Add Leetcode #5 solution

### PR DESCRIPTION
**Pull request by ongzx**
# Pull Request Template

## Description

This PR adds the solution for Leetcode #5. Written in Javascript.

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lokendra1704 — CHANGES_REQUESTED** [review]
Update Readme. Make sure the solution for same question in same language is not already there.

**Comment by ongzx** [comment]
@lokendra1704 done.

**Comment by GouravRusiya30** [comment]
Readme is not correctly updated

**Comment by ongzx** [comment]
@GouravRusiya30 possible to tag it with `hacktoberfest-accepted`?

**Pull request merged**
