### PR TITLE
Added python code for 189. Rotate Array & 137. Single Number II

### PR DESCRIPTION
**Pull request by jameszu**
# Rotate Array & Single Number II

#### Rotate Array:
```
Given an array, rotate the array to the right by k steps, where k is non-negative.
Follow up:
Try to come up as many solutions as you can, there are at least 3 different ways to solve this problem.
Could you do it in-place with O(1) extra space?
```
Idea:
One way is to append the first (length-k) elements to the back, and delete the first (length-k) elements in the array. <br>
#### Single Number II:
```
Given a non-empty array of integers, every element appears three times except for one, which appears exactly once. 
Find that single one.
```
Idea:
One way is to use hashtable and count how many elements repeated and the one with 1 would be the return value.
Or bitwise way think a[i]b[i] as a binary number, to indicate (the sum of all i-th bit of num) % 3.
You can use num[0:2] as a, b just with slight changes. Finally after a loop the b would be our return value.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
#### Rotate Array:
- [x] Input: [1,2,3,4,5,6,7]
3
Expected output: [5,6,7,1,2,3,4]
- [x] Input: [-1,-100,3,99]
2
Expected output: [3,99,-1,-100]
#### Single Number II
- [x] Input: [2,2,3,2] Expected output: 3
- [x] Input: [0,1,0,1,0,1,99] Expected output: 99
## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by GouravRusiya30** [comment]
@jameszu We already have good collections on array problems.
Can you contribute to some other topic ?

**Comment by jameszu** [comment]
Okay sure I will look into others

**Comment by GouravRusiya30** [comment]
@jameszu Thanks !!!
I will wait for more solutions before merging this PR

**Comment by jameszu** [comment]
@GouravRusiya30 Okay I've contributed another question

**Comment by GouravRusiya30** [comment]
Nice !!!
Merging this PR

**Pull request merged**
