### PR TITLE
Add solution for leetcode #152 in javascript

### PR DESCRIPTION
**Pull request by ongzx**
# Pull Request Template

## Description

This PR adds solution to leetcode question #152 in Javascript.

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lokendra1704 — CHANGES_REQUESTED** [review]
Update Readme

**Comment by ongzx** [comment]
@lokendra1704 done.

**Comment by GouravRusiya30** [comment]
One suggestion @ongzx 
Try to put all new changes in a single PR, instead of these many PRs

**Comment by ongzx** [comment]
@GouravRusiya30 possible to tag it with `hacktoberfest-accepted`?

**Pull request merged**
