### PR TITLE
Adding solution of Arithmetic Subarrays

### PR DESCRIPTION
**Pull request by SauravP97**
# Pull Request Template

- Problem Name : **Arithmetic Subarrays**

- Summary : We have been asked **Q** queries. Every query has a range l and r and we have to tell whether the array elements from **l** to **r** form an Arithmetic Sequence. The idea is to find the **maximum** and **minimum** element of the sub array for every query and divide the difference of maximum and minimum element into **(maximum - minimum)/x** equal parts, where x is the size of the sub array.
Now we jump to every part and check whether the given part is present in the sub array. For this we can use a hash set, I have used index based hashing in the array to save some time.  :smile: 

- Difficulty : **Medium**

## Description

Please include a summary of the problem and about the approach to solve the solution. Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Have you made changes in [README](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/README.md) file ?
- [x] Added problem & solution under correct topic.
- [x] Specified Space & Time complexity.
- [x] Specified difficulty level, tag & Note(if any).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Make sure all below guidelines are followed else PR will get Reject:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code so that it is easy to understand
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SauravP97** [comment]
Hey @GouravRusiya30,
      We can add a block of editorial or summary of the solution for the Problem in the code file as well. Because, simply looking at the code solution won't help the beginner programmers much. If there is a gist or an idea of how the problem can be approached and solved then it would help others a lot.
      I have tried to put my editorial for the Problem in the solution code as comments.

**Comment by GouravRusiya30** [comment]
@SauravP97 
I totally Agree with your point !!!
Infact that;s what @lokendra1704 Also suggested initially & he always put the editorial in the solution code as comments.

Please suggest if you have some template for the editorial for our git repo.

Once again thanks Saurav for Contributing !!!

**Comment by SauravP97** [comment]
> @SauravP97
> I totally Agree with your point !!!
> Infact that;s what @lokendra1704 also suggested initially & he always put the editorial in the solution code as comments.
> 
> Please suggest if you have some template for the editorial for our git repo.
> 
> Once again thanks Saurav for Contributing !!!

**Comment by SauravP97** [comment]
Okay @GouravRusiya30 ,
  I will look into it. If I find anything worth sharing, I will let you know,

P.S. Sorry I accidentally closed the PR, I have reopened it now !

**Comment by GouravRusiya30** [comment]
@SauravP97 
No problem !!!
I will be happy to discuss that & feel free to join our telegram group - https://t.me/codedecksgrp

I will be Happy if you want to be part of that grp :)

**Review by GouravRusiya30 — APPROVED** [review]

**Comment by SauravP97** [comment]
Sure @GouravRusiya30, I would love to be a part of the group :grinning:

**Pull request merged**
